### ISSUE TITLE
Question on wif-keys.csv

### ISSUE THREAD

**Issue by geopayme** [shayanb/Bitcoin-PoS-PHP#3]
I was curious, where is this file created, since I do not see any comments, but when I use the admin section to read keys I get the message that "Your wif-keys.csv file does not exist."

What keys are kept in the file? Private or Public?

Any thoughts?

**Comment by shayanb** [comment]
have you generated the RSA keys and added them to the config file?

the wif-keys.csv are the encrypted private keys saved in a file. Bitcoin SCI was using only file based storage system (no database) and I added the database support and kept most of the file based features as a backup option. 

and also you should know that this file is generated when the first key is generated and that is on the first request for transaction, and I guess yours is failing because of https://github.com/shayanb/Bitcoin-PoS-PHP/issues/1

**Comment by geopayme** [comment]
I did create the key and added the PUB key to the config file. But I don't see where the wif-keys.csv file is stored. 

I checked the DB and searched the server path not wif-keys.csv. Any thoughts

**Comment by shayanb** [comment]
so basicly the file should be under /sci directory. I had the same issue at first and changing the permission of the directories to 755 solved the issue.
do you have the wifs in the database?

**Comment by geopayme** [comment]
Creating the t_data directory and cmod() 777 made all the difference. Issue fixed
