### ISSUE TITLE
Incomplete Transaction Question

### ISSUE THREAD

**Issue by geopayme** [shayanb/Bitcoin-PoS-PHP#4]
Since I had the error from my previous posting, I see this message, when I click on the link to complete the transaction I receive this error "No input file specified."

I am sure the message is handled by a cookie that can be deleted, is there a place to see incomplete transactions? or all of it is related to the previous posted error about the incomplete transaction.

![btc-error](https://cloud.githubusercontent.com/assets/8299759/7198924/0aae519a-e4f9-11e4-9a4b-dde564b570b3.jpg)

**Comment by shayanb** [comment]
this is related to the cookie that still has not expired and looks for the previous transaction, and because of https://github.com/shayanb/Bitcoin-PoS-PHP/issues/1 you don't have anything saved in the file and it cannot find the previously failed transaction.
you can just delete the cookies and this error will be gone, or continue to a new transaction.

**Comment by geopayme** [comment]
I understand, but you are referencing a "file", what file and how do I know that something is saved in it... sissy silly question, trying to understand the flow.

**Comment by shayanb** [comment]
same as the other one, change the permission of the directories to 755 and give it a try. also check if the owner of the directories are the same

**Comment by geopayme** [comment]
ok changed the t_data to 777 and it works fine now... I still have questions but I will work thru the flow before I ask.

![btc-sale](https://cloud.githubusercontent.com/assets/8299759/7208003/4158ea28-e546-11e4-96a7-59d926d6d844.jpg)

**Comment by shayanb** [comment]
Great. I'll add it to the readme.md then :)
